// Code generated by the Gleam compiler. DO NOT EDIT.
//
// Go-target prelude for Gleam's built-in operations that need different
// semantics from the underlying Go operator. Kept minimal on purpose — the
// full Gleam runtime lands in a later milestone.
package prelude

// DivInt returns zero when the divisor is zero, matching Gleam's semantics
// for the `/` operator on Int. Go's native `/` panics on division by zero.
func DivInt(a, b int64) int64 {
	if b == 0 {
		return 0
	}
	return a / b
}

// RemInt is the Gleam-semantics counterpart to `%`, returning zero when the
// divisor is zero instead of panicking.
func RemInt(a, b int64) int64 {
	if b == 0 {
		return 0
	}
	return a % b
}

// DivFloat returns zero when the divisor is zero, matching Gleam's semantics
// for the `/.` operator on Float.
func DivFloat(a, b float64) float64 {
	if b == 0 {
		return 0
	}
	return a / b
}
